### ISSUE TITLE
'Select A' instead of the option name

### ISSUE THREAD

**Issue by connecticus** [AgilTec/spree_variant_options#9]
instead of the option name, such as size, color, etc., is displayed 'Select A'

AgilTec/spree_variant_options 2-4-stable

**Comment by connecticus** [comment]
I fix this, problem in missing translations.

**Comment by rsempe** [comment]
@connecticus Could you tell me how you fix this exactly? I have the same problem.

**Comment by connecticus** [comment]
Hi @rsempe! Just add translations for your lang :)
